### ISSUE TITLE
queue.remove() not working as intended? 

### ISSUE THREAD

**Issue by pab14567** [Solaris9/erela.js#76]
Hi! I'm not sure If I'm reading it wrong or using it improperly, but I'm trying to let the users choose what track to remove from the queue and no matter what number the user replies with, it only removes the next track after the current one playing. It does not remove the specified track. 

<code>
player.queue.remove(args[0])
</code>

is what I'm using, if you need more let me know!

Any ideas?  (Using up to date version of erela.js)

**Comment by T3NED** [comment]
The `queue#remove` method is working perfectly. Note the current playing track is not included when removing tracks from the queue (written in CAPS in the documentation). Queue index starts at 0. Hope this helps!

**Comment by pab14567** [comment]
Yeah! 
args[0] is whatever the user inputs and i've been putting  higher than 0 and there's 12 songs on the queue. I'm trying to remove the 6th song in the queue, but no matter what number i put into the remove() method, it only removes the first track on the queue.

**Comment by Solaris9** [comment]
Doing some tests it seems like providing `undefined` which you are most likely doing will remove only the first element in the array, this is because JavaScript treats all falsy values as the number 0 literally. You will probably say you're not giving `undefined` but JavaScript doesn't care what you do if you try to access a `undefined` (no value defined) value, this includes array elements and properties. You should check what the user is providing beforehand, if it exists, if it's a number, if it's in range of the queue, if all of those don't fail then remove it from the queue. Another good solution for long time would be to use TypeScript as it will catch basically all these errors and hint towards better code.

**Comment by RedfurREBORN** [comment]
I would like to point out that args[0] is probably a string. Try convert it before you remove it. Something like this

`
const index = number(args[0]) || 0 
player.queue.remove(index)
`
Note that the the `||` was added incase it failed to convert

**Comment by pab14567** [comment]
I actually just realized my mistake, I'm an idiot. 

I wasn't getting the track correctly, and it was returning the first track in the queue, rather than the track I was removing. 

Thanks for the help! Sorry for the bother

**Comment by Solaris9** [comment]
> I would like to point out that args[0] is probably a string. Try convert it before you remove it. Something like this
> 
> `const index = Number(args[0]) || 0 `
> `player.queue.remove(index)`
> Note that the the `||` was added incase it failed to convert

It being a number does not matter with JavaScript, however I will be adding more strict types so this won't be an issue.
